server.port: 9091
spring:
  kafka:
    consumer:
      properties:
        isolation.level: read_committed
        max.poll.records: 100
        enable.auto.commit: false

  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: localhost:9092
          reset-offsets: true
          start-offset: latest
        bindings:
          techforum-in:
             consumer:
                autoCommitOffset: false
      bindings:
        techforum-in:
          destination: techforum-topic
          contentType: application/json
          group: techforum-group-two
          client: techforum-client-two
          autoCommitOffset: false
        techforum-out:
          destination: techforum-topic
          contentType: application/json
          group: techforum-group-two
          client: techforum-client-two
          autoCommitOffset: false